name: Unit Tests

on: ["push", "pull_request"]

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      INVENTREE_SITE_URL: http://localhost:8000
      INVENTREE_DB_ENGINE: django.db.backends.sqlite3
      INVENTREE_DB_NAME: ../inventree_unit_test_db.sqlite3
      INVENTREE_MEDIA_ROOT: ../test_inventree_media
      INVENTREE_STATIC_ROOT: ../test_inventree_static
      INVENTREE_BACKUP_DIR: ../test_inventree_backup
      INVENTREE_COOKIE_SAMESITE: False
      INVENTREE_ADMIN_USER: testuser
      INVENTREE_ADMIN_PASSWORD: testpassword
      INVENTREE_ADMIN_EMAIL: test@test.com
      INVENTREE_PYTHON_TEST_SERVER: http://localhost:12345
      INVENTREE_PYTHON_TEST_USERNAME: testuser
      INVENTREE_PYTHON_TEST_PASSWORD: testpassword
      INVENTREE_DEBUG: True

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Deps
        run: |
          pip install -U -r requirements.txt
      - name: Start InvenTree Server
        run: |
          sudo apt-get install python3-dev python3-pip python3-venv python3-wheel g++
          pip3 install invoke
          git clone --depth 1 https://github.com/inventree/inventree ./inventree_server
          cd inventree_server
          invoke install
          invoke migrate
          invoke dev.import-fixtures
          invoke dev.server -a 0.0.0.0:12345 &
          invoke wait
      - name: Run Tests
        run: |
          invoke check-server -d
          coverage run -m unittest discover -s test/
      - name: Upload Report
        run: |
          coveralls --service=github
