name: Unit Tests

on: ["push", "pull_request"]

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      INVENTREE_DB_ENGINE: django.db.backends.sqlite3
      INVENTREE_DB_NAME: ../inventree_unit_test_db.sqlite3
      INVENTREE_MEDIA_ROOT: ../test_inventree_media
      INVENTREE_STATIC_ROOT: ../test_inventree_static

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Deps
        run: |
          pip install -U -r requirements.txt
      - name: Start InvenTree Server
        run: |
          sudo apt-get install python3-dev python3-pip python3-venv python3-wheel g++
          pip3 install invoke
          git clone --depth 1 https://github.com/inventree/inventree ./inventree_server
          cd inventree_server
          invoke install
          invoke migrate
          invoke import-fixtures
          invoke server -a http://localhost:12345 &
          invoke check-server
      - name: Run Tests
        run: |
          coverage run -m unittest discover -s test/
      - name: Upload Report
        run: |
          coveralls